ALTER TABLE DataDescription ADD COLUMN 'CANid'          INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DataDescription ADD COLUMN 'CANmsgPosition' INTEGER NOT NULL DEFAULT 1;
ALTER TABLE DataDescription ADD COLUMN 'CANbyteLength'  INTEGER NOT NULL DEFAULT 1;
ALTER TABLE DataDescription ADD COLUMN 'CANscale'       NUMBER NOT NULL DEFAULT  1;
ALTER TABLE DataDescription ADD COLUMN 'Endian'         INTEGER NOT NULL DEFAULT  0;